/**
 * Every consumer-facing concierge string. House register: one or two sentences,
 * no exclamation marks, no software vocabulary, facts only as published.
 */
export const CONCIERGE = {
  name: 'Waseem Concierge',
  sub: 'Private jewellery assistance',
  placeholder: 'Ask about a piece, a collection or a private appointment.',
  youMightAsk: 'You might ask',
  suggestions: ['Show me bridal necklaces', 'Something traditional', 'A private consultation'],
  spokenReplies: 'Spoken replies',
  beginAgain: 'Begin again',
  letMeShowYou: 'Let me show you',
  youMightSay: 'you might say —',
  voice: {
    ready: 'Speak when you are ready.',
    listening: 'Listening.',
    thinking: 'A moment.',
    speaking: 'Speaking.',
    executing: 'One moment.',
    stop: 'Stop listening',
    start: 'Speak to the concierge',
    unavailable: 'Voice is written here; touch the ring and I will show you.',
  },
  greeting: (hour: number) => `${hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'}. I am the Waseem Concierge — ask about a piece, a collection or a private appointment.`,
  greetingAgain: 'Still here. What would you like to see?',
  thanks: 'A pleasure.',
  close: 'Until next time.',
  help: 'I can bring pieces to you, open a collection, keep a piece in your selection, or arrange a private viewing.',
  unknown: 'I may have missed that. I can show you pieces, open a collection or arrange a private viewing.',
  outOfScope: 'That is beyond the house, I am afraid. I can help with pieces, collections and private appointments.',
  watches: "The house's watch salon is best seen in person at MM Alam Road — shall I arrange a visit?",
  micDenied: 'Your microphone is switched off for this site. You can write to me instead, or let me show you.',
  noSpeech: 'I did not catch that — once more, a little closer.',
  error: 'Forgive me — shall we try that once more?',
  errorLink: 'once more',
  house: 'Waseem Jewellers was founded in Lahore in 1952 by Chaudhry Muhammad Afzal, and receives visitors today at three showrooms across the city.',
  showrooms: 'Three showrooms in Lahore — MM Alam Road, Liberty Market and DHA — open from noon until half past nine.',
  collections: 'Five worlds — Rukh-e-Jana, Aks-e-Noor, Rang-e-Jamal, Dewan and Royal Wedding. Say a name and I will take you there.',
  bridal: 'The Bridal House. Take your time — I am here if a piece speaks to you.',
  diamond: 'Our diamond pieces — pavé, cluster and uncut stones. Shall I open one?',
  gold: 'Kundan, polki and pleated gold. Shall I open one?',
  traditional: 'For a traditional hand I would begin with polki and kundan — these are closest to how the house has always worked.',
  consultation: 'With pleasure. Choose a showroom and a time that suits you — MM Alam Road, Liberty or DHA.',
  consultationKnown: (code: string) => `Your request ${code} is with the House. I can arrange a further viewing whenever you wish.`,
  priceOnRequest: 'This piece is priced on request — the house shares full details at a private viewing, which I can arrange.',
  priceKnown: (label: string, karat?: string) => `This piece is ${label}${karat ? `, in ${karat}` : ''}. Shall I arrange a viewing?`,
  saved: 'Kept in your selection. It will be here when you return.',
  alreadySaved: 'That one is already in your selection.',
  removed: 'Removed from your selection.',
  whichPiece: 'Which piece would you like? I can bring the bridal pieces first.',
  whichPieceToSave: 'Which piece shall I keep for you? Open one, or tell me its name.',
  whichPieceSimilar: 'Show me the piece you have in mind and I will find its company.',
  opened: (name: string) => `Here it is — the ${name}.`,
  similar: 'Four pieces in the same spirit — the same stones, a different hand.',
  similarCount: (n: string) => `${n} pieces in the same spirit — the same stones, a different hand.`,
  world: (name: string, mood: string) => `${name} — ${mood.replace(/\.$/, '').toLowerCase()}. I will leave you with it.`,
  searchResult: (count: string, what: string, houses: string[]) =>
    houses.length > 1
      ? `${count} ${what}, drawn from ${houses.slice(0, -1).join(', ')} and ${houses[houses.length - 1]}. Tell me which one draws you.`
      : `${count} ${what}. Tell me which one draws you.`,
  nothing: 'Nothing quite like that in the house today. Shall I show you the bridal pieces instead?',
  wishlistEmpty: 'Your selection is empty for now. Say "keep this" when a piece speaks to you.',
  wishlist: (n: string) => `${n} pieces so far. Shall I open one, or arrange a viewing for them?`,
  tellAbout: (name: string, lede: string) => `The ${name}: ${lede.charAt(0).toLowerCase()}${lede.slice(1)}`,
  tellAboutSpecs: (name: string, lede: string, specs: string) => `The ${name}: ${lede.charAt(0).toLowerCase()}${lede.slice(1)} ${specs}`,
  selectionIntro: (names: string[]) => `Your selection holds ${names.join(', ')}. Shall I arrange a viewing for them?`,
  labels: {
    searching: (what: string) => `Exploring ${what}…`,
    found: (count: string, what: string) => `${count} ${what}`,
    nothing: 'Nothing quite like that',
    opening: (name: string) => `Opening ${name}…`,
    opened: (name: string) => name,
    showing: (name: string) => `Showing the ${name}…`,
    shown: (name: string) => name,
    similar: 'Pieces in the same spirit…',
    similarDone: (count: string) => `${count} pieces in the same spirit`,
    keeping: 'Keeping this piece…',
    kept: 'Saved to your selection',
    alreadyKept: 'Already in your selection',
    removing: 'Setting it aside…',
    removed: 'Removed from your selection',
    selection: 'Your selection…',
    selectionDone: (n: string) => `Your selection · ${n} pieces`,
    selectionEmpty: 'Your selection is empty',
    consultation: 'Arranging a private consultation…',
    consultationDone: 'Private consultation',
    bridal: 'Exploring Bridal…',
    bridalDone: 'The Bridal House',
    gold: 'Exploring Gold…',
    goldDone: 'Gold',
    diamond: 'Exploring Diamond…',
    diamondDone: 'Diamond',
    going: (label: string) => `Taking you to ${label}…`,
    gone: (label: string) => label,
    navigating: (label: string) => `Opening ${label}…`,
  },
} as const;
