/**
 * Stage 3 of the brand pipeline: turn the traced bands into the authored mark.
 *
 * What this does that the trace does not:
 *   - optimises each contour through svgo (relative commands, integer coordinates)
 *   - splits each band's single monolithic path into an outer silhouette and its
 *     counters, so the mark can be drawn (stroke the silhouette) as well as filled
 *   - names the parts, which is what makes it a brand system rather than a blob
 *
 * The geometry itself is Waseem's, unaltered. Reconstructing this knotwork by hand
 * from a 73px source would risk redesigning the identity into something adjacent;
 * the trace measures ~0.97 IoU against the master, so it is followed, not redrawn.
 *
 * Coordinates stay in 8x band-pixel space, so every value is an integer at 1/8
 * master-pixel precision and no float ever reaches the bundle.
 *
 *   node scripts/brand/assemble.mjs
 */
import { Potrace } from 'potrace';
import { optimize } from 'svgo';
import fs from 'node:fs/promises';
import path from 'node:path';
import { BANDS, SCALE, CACHE, MASTER_SIZE, box, bandById } from './lib.mjs';

const IN = path.join(CACHE, 'bands');
const BRAND_DIR = path.join(process.cwd(), 'src/components/brand');

/** Near-best IoU with meaningful node reduction; the sweep showed the space is flat. */
const PARAMS = { turdSize: 2, alphaMax: 1.0, optTolerance: 0.5, threshold: 128, blackOnWhite: true, turnPolicy: Potrace.TURNPOLICY_MINORITY };

const trace = (id) =>
  new Promise((resolve, reject) => {
    const p = new Potrace(PARAMS);
    p.loadImage(path.join(IN, `${id}.png`), (err) => (err ? reject(err) : resolve(p.getSVG())));
  });

const nodesOf = (d) => (d.match(/[MLCQAZmlcqazSsTtHhVv]/g) ?? []).length;

/** svgo at integer precision. Input coordinates are 8x, so an integer is 1/8 master pixel. */
function compress(d, width, height) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}"><path d="${d}"/></svg>`;
  const out = optimize(svg, {
    multipass: true,
    floatPrecision: 0,
    plugins: [
      { name: 'preset-default', params: { overrides: { removeViewBox: false } } },
      { name: 'convertPathData', params: { floatPrecision: 0, transformPrecision: 0, makeArcs: false, straightCurves: true, curveSmoothShorthands: true, utilizeAbsolute: true } },
    ],
  });
  const m = out.data.match(/ d="([^"]+)"/);
  return m ? m[1] : d;
}

/** potrace emits one path of many closed contours; the largest by extent is the silhouette. */
function splitSubpaths(d) {
  const subs = d.split(/(?=M)/).map((s) => s.trim()).filter(Boolean);
  const scored = subs.map((s) => {
    const nums = (s.match(/-?\d*\.?\d+/g) ?? []).map(Number);
    let x0 = Infinity;
    let y0 = Infinity;
    let x1 = -Infinity;
    let y1 = -Infinity;
    for (let i = 0; i + 1 < nums.length; i += 2) {
      x0 = Math.min(x0, nums[i]); x1 = Math.max(x1, nums[i]);
      y0 = Math.min(y0, nums[i + 1]); y1 = Math.max(y1, nums[i + 1]);
    }
    return { d: s, extent: (x1 - x0) * (y1 - y0) };
  });
  const outer = scored.reduce((best, s) => (s.extent > best.extent ? s : best), scored[0]);
  return { outline: outer.d, all: scored.map((s) => s.d).join(''), count: scored.length };
}

const geometry = {};
for (const band of BANDS) {
  const b = box(band);
  const w = b.width * SCALE;
  const h = b.height * SCALE;
  const svg = await trace(band.id);
  const parts = splitSubpaths(svg.match(/ d="([^"]+)"/)[1]);
  const fill = compress(parts.all, w, h);
  const outline = compress(parts.outline, w, h);
  geometry[band.id] = { fill, outline, w, h, subpaths: parts.count, nodes: nodesOf(fill) };
  console.log(
    `${band.id.padEnd(9)} ${String(parts.count).padStart(2)} contours  ${String(nodesOf(fill)).padStart(4)} nodes  fill ${String(fill.length).padStart(5)}ch  outline ${String(outline.length).padStart(5)}ch`,
  );
}

const viewBoxOf = (id) => `0 0 ${geometry[id].w} ${geometry[id].h}`;
/** Where each band sits inside the lockup, in 8x space. */
const offsetOf = (id) => ({ x: box(bandById(id)).left * SCALE, y: box(bandById(id)).top * SCALE });

const header = (what) => `/* Generated by scripts/brand/assemble.mjs from scripts/brand/master/waseem-logo.png — do not edit.
 *
 * ${what}
 *
 * Coordinates are integers in 8x master-pixel space (1 unit = 1/8 of a master pixel),
 * so every variant shares one geometry and no float reaches the bundle.
 * \`fill\` is the complete shape and must be drawn with fill-rule="evenodd";
 * \`outline\` is the outer silhouette alone, for stroke-dasharray drawing.
 *
 * Fidelity is gated by scripts/brand/verify.mjs (npm run brand:check), which is
 * necessary but not sufficient — the mark also carries written human sign-off.
 */\n`;

const decl = (id) => `/** ${id} — ${geometry[id].subpaths} contours, ${geometry[id].nodes} nodes. */
export const ${id.replace(/-/g, '_').toUpperCase()} = {
  viewBox: '${viewBoxOf(id)}',
  offset: ${JSON.stringify(offsetOf(id))},
  fill: '${geometry[id].fill}',
  outline: '${geometry[id].outline}',
} as const;`;

// The mark proper: crest + WJW. Used by the favicon, nav, footer, watermark and the ritual.
const markFile = `${header('Waseem Jewellers’ mark: the crest and the WJW ligature.')}
export const MARK_SOURCE = ${JSON.stringify({ file: 'scripts/brand/master/waseem-logo.png', ...MASTER_SIZE })} as const;

/** The whole lockup in 8x space, for variants that place bands by offset. */
export const LOCKUP_VIEWBOX = '0 0 ${MASTER_SIZE.width * SCALE} ${MASTER_SIZE.height * SCALE}';

/** The mark's vertical mirror axis, in 8x space. */
export const AXIS = ${499 * SCALE};

${decl('crest')}

${decl('monogram')}

/** Crest above ligature, cropped to the two of them. */
export const CREST_MONOGRAM_VIEWBOX = '${offsetOf('monogram').x} ${offsetOf('crest').y} ${geometry.monogram.w} ${offsetOf('monogram').y + geometry.monogram.h - offsetOf('crest').y}';

export const MARK_NODES = ${JSON.stringify({ crest: geometry.crest.nodes, monogram: geometry.monogram.nodes })} as const;
`;

// The wordmark: two lines of geometric caps. Only the full lockup needs it, so it is a
// separate module and stays out of any chunk that only shows the mark.
const wordFile = `${header('The “WASEEM JEWELLERS” wordmark, two lines. Imported only by the full lockup.')}
${decl('word-1')}

${decl('word-2')}

export const WORDMARK_NODES = ${JSON.stringify({ 'word-1': geometry['word-1'].nodes, 'word-2': geometry['word-2'].nodes })} as const;
`;

await fs.mkdir(BRAND_DIR, { recursive: true });
await fs.writeFile(path.join(BRAND_DIR, 'markGeometry.ts'), markFile, 'utf8');
await fs.writeFile(path.join(BRAND_DIR, 'wordmarkGeometry.ts'), wordFile, 'utf8');
console.log(`\n→ src/components/brand/markGeometry.ts      ${(markFile.length / 1024).toFixed(1)} kB`);
console.log(`→ src/components/brand/wordmarkGeometry.ts  ${(wordFile.length / 1024).toFixed(1)} kB`);

// a candidate lockup for verify.mjs, bands placed by offset
const layers = BANDS.map((band) => {
  const o = offsetOf(band.id);
  return `<g transform="translate(${o.x} ${o.y})"><path fill="#dbb45d" fill-rule="evenodd" d="${geometry[band.id].fill}"/></g>`;
}).join('');
const candidate = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MASTER_SIZE.width * SCALE} ${MASTER_SIZE.height * SCALE}" width="${MASTER_SIZE.width}" height="${MASTER_SIZE.height}">${layers}</svg>`;
await fs.writeFile(path.join(CACHE, 'candidate.svg'), candidate, 'utf8');
console.log(`→ ${path.relative(process.cwd(), path.join(CACHE, 'candidate.svg'))}  ${(candidate.length / 1024).toFixed(1)} kB`);
